/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_whackamole_GameOver */

#ifndef _Included_com_example_whackamole_GameOver
#define _Included_com_example_whackamole_GameOver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_whackamole_GameOver
 * Method:    gameOver
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_whackamole_GameOver_gameOver
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_whackamole_GameOver
 * Method:    driverClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_whackamole_GameOver_driverClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
