/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_whackamole_WhackAMole */

#ifndef _Included_com_example_whackamole_WhackAMole
#define _Included_com_example_whackamole_WhackAMole
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_whackamole_WhackAMole_TOTAL_TIME
#define com_example_whackamole_WhackAMole_TOTAL_TIME 120L
#undef com_example_whackamole_WhackAMole_INITIAL_SHOW_TIME
#define com_example_whackamole_WhackAMole_INITIAL_SHOW_TIME 1500L
#undef com_example_whackamole_WhackAMole_TIME_DECREASE_INTERVAL
#define com_example_whackamole_WhackAMole_TIME_DECREASE_INTERVAL 20L
#undef com_example_whackamole_WhackAMole_TIME_DECREASE_AMOUNT
#define com_example_whackamole_WhackAMole_TIME_DECREASE_AMOUNT 150L
#undef com_example_whackamole_WhackAMole_MIN_SHOW_TIME
#define com_example_whackamole_WhackAMole_MIN_SHOW_TIME 200L
/*
 * Class:     com_example_whackamole_WhackAMole
 * Method:    driverClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_whackamole_WhackAMole_driverClose
  (JNIEnv *, jobject);

/*
 * Class:     com_example_whackamole_WhackAMole
 * Method:    readSwitchInput
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_whackamole_WhackAMole_readSwitchInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_whackamole_WhackAMole
 * Method:    loseLife
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_whackamole_WhackAMole_loseLife
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
