/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_whackamole_Start */

#ifndef _Included_com_example_whackamole_Start
#define _Included_com_example_whackamole_Start
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_whackamole_Start
 * Method:    driverOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_whackamole_Start_driverOpen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
